"""Public Network Client API.

The package deliberately exposes typed requests and immutable snapshots only.
There is no public raw-message send function.
"""

from .client import NetworkClient
from .credentials import FileCredentialStore
from .protocol import (
    PROTOCOL_VERSION,
    ProtocolMessageValidator,
    ProtocolValidationError,
    make_client_request,
)
from .types import (
    ActionHandle,
    AbilityAction,
    ActionRejected,
    ChatAction,
    ClientEvent,
    ClientExit,
    ClientExitReason,
    ClientLifecycle,
    ClientSnapshot,
    CoDeclareAction,
    CoReportAction,
    ConsumerOverrunError,
    CredentialError,
    CredentialStore,
    DeliveryUnknown,
    DeliveryUnknownError,
    FatalTermination,
    GameEnded,
    IncompatibleProtocolError,
    LifecycleChanged,
    NetworkClientConfig,
    NotDelivered,
    NotDeliveredError,
    PhaseDeadlineReached,
    ProtocolError,
    ReconnectPolicy,
    SequenceGapDetected,
    SequenceGapRecovered,
    SendReceipt,
    ServerEvent,
    SessionCheckpoint,
    StaleActionError,
    VoteAction,
)

__all__ = [
    "ActionHandle",
    "AbilityAction",
    "ActionRejected",
    "ChatAction",
    "ClientEvent",
    "ClientExit",
    "ClientExitReason",
    "ClientLifecycle",
    "ClientSnapshot",
    "CoDeclareAction",
    "CoReportAction",
    "ConsumerOverrunError",
    "CredentialError",
    "CredentialStore",
    "DeliveryUnknown",
    "DeliveryUnknownError",
    "FatalTermination",
    "FileCredentialStore",
    "GameEnded",
    "IncompatibleProtocolError",
    "LifecycleChanged",
    "NetworkClient",
    "NetworkClientConfig",
    "NotDelivered",
    "NotDeliveredError",
    "PROTOCOL_VERSION",
    "PhaseDeadlineReached",
    "ProtocolError",
    "ProtocolMessageValidator",
    "ProtocolValidationError",
    "ReconnectPolicy",
    "SequenceGapDetected",
    "SequenceGapRecovered",
    "SendReceipt",
    "ServerEvent",
    "SessionCheckpoint",
    "StaleActionError",
    "VoteAction",
    "make_client_request",
]
