"""Public, model-neutral Local LLM integration surface."""

from .audit import JsonlAiAuditSink
from .admission_broker import GenerationAdmissionBroker
from .admission_client import BrokerAdmissionSession, BrokeredStructuredLLMBackend
from .admission_metrics import (
    AdmissionMetric,
    AdmissionMetrics,
    serialize_admission_metric,
)
from .admission_types import (
    GENERATION_IPC_PROTOCOL,
    AdmissionBrokerSnapshot,
    AdmissionCredentials,
    AdmissionRequest,
    AdmissionResult,
    AdmissionStatus,
    BrokerReady,
    GenerationAdmission,
    GenerationBrokerConfig,
    GenerationLease,
    GenerationPriority,
    SuccessorReservation,
)
from .backend import OpenAICompatibleBackend, StructuredLLMBackend
from .brain import AiAuditSink, LLMBrain, LLMInvocationError
from .config import LocalLLMSettings
from .decision import DecisionValidationError, parse_llm_decision
from .prompt import PromptProjectionError, project_brain_input
from .types import (
    AiAuditDecision,
    AiAuditError,
    AiAuditErrorCode,
    AiAuditRecord,
    AiAuditStatus,
    AiAuditWriterConfig,
    AuditWriteAck,
    BackendIdentity,
    DecisionValidationCode,
    GenerationSettings,
    LLMBackendError,
    LLMBackendErrorCode,
    LLMBrainConfig,
    LLMBrainSnapshot,
    LLMClientIdentity,
    LLMInvocationStatus,
    LLMMessage,
    LLMUsage,
    OpenAICompatibleBackendConfig,
    PromptProjection,
    ProviderQuiescence,
    ProviderTiming,
    ProviderTimingDiagnostic,
    ProviderTimingFieldState,
    ProviderTimingShapeStatus,
    ShortChatConfig,
    StructuredGenerationRequest,
    StructuredGenerationResponse,
    serialize_ai_audit,
)

__all__ = [
    "GENERATION_IPC_PROTOCOL",
    "AdmissionBrokerSnapshot",
    "AdmissionCredentials",
    "AdmissionMetric",
    "AdmissionMetrics",
    "AdmissionRequest",
    "AdmissionResult",
    "AdmissionStatus",
    "AiAuditDecision",
    "AiAuditError",
    "AiAuditErrorCode",
    "AiAuditRecord",
    "AiAuditSink",
    "AiAuditStatus",
    "AiAuditWriterConfig",
    "AuditWriteAck",
    "BackendIdentity",
    "BrokerAdmissionSession",
    "BrokerReady",
    "BrokeredStructuredLLMBackend",
    "DecisionValidationCode",
    "DecisionValidationError",
    "GenerationSettings",
    "GenerationAdmission",
    "GenerationAdmissionBroker",
    "GenerationBrokerConfig",
    "GenerationLease",
    "GenerationPriority",
    "JsonlAiAuditSink",
    "LLMBackendError",
    "LLMBackendErrorCode",
    "LLMBrain",
    "LLMBrainConfig",
    "LLMBrainSnapshot",
    "LLMClientIdentity",
    "LLMInvocationError",
    "LLMInvocationStatus",
    "LLMMessage",
    "LLMUsage",
    "LocalLLMSettings",
    "OpenAICompatibleBackend",
    "OpenAICompatibleBackendConfig",
    "PromptProjection",
    "PromptProjectionError",
    "StructuredGenerationRequest",
    "StructuredGenerationResponse",
    "StructuredLLMBackend",
    "ProviderQuiescence",
    "ProviderTiming",
    "ProviderTimingDiagnostic",
    "ProviderTimingFieldState",
    "ProviderTimingShapeStatus",
    "ShortChatConfig",
    "SuccessorReservation",
    "parse_llm_decision",
    "project_brain_input",
    "serialize_ai_audit",
    "serialize_admission_metric",
]
