id: fanatic
description: "狂信者。人間ですが、人狼陣営の勝利を目指します。サーバの仲間通知で人狼を知っています。占い結果は人狼ではないと出ます。所属を隠してください。嘘や役職の騙りは許されています。"
name: 狂信者
claimable: true
team: wolf
count_as: village
attack_result: die
inspect_result: not_wolf
medium_result: not_wolf
tags: []
knows_teammates: true
chat_channels: [public]
abilities: []
passives: []
options: {}
