id: madman
name: 狂人
team: wolf
count_as: village
attack_result: die
inspect_result: not_wolf
medium_result: not_wolf
tags: []
knows_teammates: false
chat_channels: [public]
abilities: []
passives: []
options: {}
