id: madman
description: "狂人。人間ですが、人狼陣営の勝利を目指します。人狼の正体は知りません。占い結果は人狼ではないと出ます。所属を隠してください。嘘や役職の騙りは許されています。"
name: 狂人
claimable: true
team: wolf
count_as: village
attack_result: die
inspect_result: not_wolf
medium_result: not_wolf
tags: []
knows_teammates: false
chat_channels: [public]
abilities: []
passives: []
options: {}
